# Generated by Django 5.2.8 on 2025-11-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='monto_final_caja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='monto_inicial_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
