# Generated by Django 5.2.7 on 2025-11-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('alquiler', 'Alquiler'), ('servicios', 'Servicios (luz, agua, gas)'), ('salarios', 'Salarios'), ('marketing', 'Marketing y Publicidad'), ('mantenimiento', 'Mantenimiento'), ('suministros', 'Suministros'), ('transporte', 'Transporte'), ('impuestos', 'Impuestos y Licencias'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('es_recurrente', models.BooleanField(default=False, help_text='Si es un gasto mensual fijo')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de producción/compra del producto', max_digits=10, null=True),
        ),
    ]
