# Generated by Django 5.2.8 on 2025-11-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
