# Generated by Django 5.2.8 on 2025-11-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_turno_monto_final_caja_turno_monto_inicial_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.lote'),
        ),
    ]
