# Generated by Django 5.2.7 on 2025-11-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_gastooperativo_producto_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
