# Generated by Django 5.2.8 on 2025-11-24 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_empleado_usuario_alter_venta_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='referencia',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='Desconocido', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='clave',
            field=models.CharField(default='0000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(default='Sin_clave', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.venta'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fono',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.producto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.empleado'),
        ),
    ]
