# Generated by Django 5.2.8 on 2025-11-16 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_cliente_correo_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pos.empleado'),
        ),
    ]
