# Generated by Django 5.2.8 on 2025-11-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_producto_codigo_barra_venta_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caducidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='elaboracion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_maximo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField()),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='pos.producto')),
            ],
        ),
    ]
