# Generated by Django 5.2.8 on 2025-12-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_producto_codigo_barra_and_more'),
        ('pos', '0009_alter_turno_hora_salida'),
    ]

    operations = [
    ]
